; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  fastled/FastLED
; slower cpu means better battery life and slightly slower execution
board_build.f_cpu = 80000000L
; zigbee needs its own partitions for the network storage
board_build.partitions = zigbee_zczr.csv

; difficulty
[difficulty]
easy = -D EASY
hard = -D HARD

; mode
[mode]
coordinator = -D COORDINATOR -D ZIGBEE_MODE_ZCZR -lesp_zb_api.zczr -lzboss_stack.zczr -lzboss_port.native

; board defines
;  if you add a board remember to add the led pin to include/rfhsledmacros.h
;  only boards with an 802.15.4 radio can run this
[seeed-xiao-esp32c5]
board = seeed_xiao_esp32c5
; using the fork from pioarduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_flags = -DARDUINO_USB_CDC_ON_BOOT=1

; actual targets, two per board
[env:seeed-xiao-esp32c5-easy-coordinator]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.easy} ${mode.coordinator} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-hard-coordinator]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.hard} ${mode.coordinator} ${seeed-xiao-esp32c5.board_flags}
