#!/bin/bash
set -e
set -u

threewords() {
  if [ ! -r '/usr/share/dict/cracklib-words' ]; then
    printf 'Unable to find /usr/share/dict/cracklib-words\n'
    exit 1
  fi
  dictionary='/usr/share/dict/cracklib-words'
  shuf -n3 "${dictionary}" | tr '[:lower:]' '[:upper:]' | paste -sd ' ' | dos2unix
}
export -f threewords

create_report() {
  printf "Formatting with conference name for %s... " "${conf}"
  sed -i \
    -e "/RFHS_CHALLENGE_NAME/{h; s/.*/printf -- '-\\n----------------------------------------------------------------\\nConference: %s\\n' \"${conf}\"/e; G;}" \
    "${conf}.txt"
  printf "complete\n"

  printf "Adding instructions..."
  sed -i -e "/FOX_KEYWORDS/{h; s/.*/printf -- '\n%s\n\n' \"\$(cat foxhunt_instructions.txt)\"/e; G;}" "${conf}.txt"
  printf "complete\n"

  printf "Seeding keys for %s... " "${conf}"
  #this works despite shell check thinking it does not
  #shellcheck disable=2016
  sed -i -e 's/\(.*\)[F]OXFLAG\(.*\)/printf "%s%s%s\\n" \x22\1\x22 "\$(threewords)" \x22\2\x22/e' "${conf}.txt"
  printf "complete\n"

  sed -i '1iSet font to "Roboto Mono"' "${conf}.txt"

  printf "Generation Complete\n"
}

# Ensure we have a conference name
if [ -n "${1:-}" ]; then
  conf="${1}"
else
  printf "Please provide conference name\n"
  exit 1
fi
for challenge in bluetooth/iBeacon bluetooth/classic_discoverable wifi/wifi_ap_client non-kitsune-foxes/fm_fox; do
  pushd "${challenge}" > /dev/null 2>&1
  grep -e 'RFHS_CHALLENGE_NAME\|FOX_KEYWORDS\|NAME\|UUID\|MAC_ADDR\|FSSID\|CHANNEL' "src/conferences/${conf}.h" | \
    sed -e 's#{##' -e 's#}##' -e 's#0x##g' -e 's#, #:#g' -e 's#// ##' -e "s/#define //" | tee -a "${OLDPWD}/${conf}.txt" > /dev/null 2>&1
  printf "complete\n"
  popd > /dev/null 2>&1
done
create_report
