#!/bin/sh
until ls /dev/ttyACM0 > /dev/null 2>&1 || ls /dev/ttyUSB0 > /dev/null 2>&1; do
  sleep 0.1
done
if ls /dev/ttyACM0 > /dev/null 2>&1; then
  stty -F /dev/ACMUSB0 115200 raw -echo
  cat /dev/ttyACM0
fi
if ls /dev/ttyUSB0 > /dev/null 2>&1; then
  stty -F /dev/USB0 115200 raw -echo
  cat /dev/ttyUSB0
fi
