#!/bin/bash
set -e
set -u

threewords() {
  if [ ! -r '/usr/share/dict/cracklib-words' ]; then
    printf 'Unable to find /usr/share/dict/cracklib-words\n'
    exit 1
  fi
  dictionary='/usr/share/dict/cracklib-words'
  shuf -n3 "${dictionary}" | tr '[:lower:]' '[:upper:]' | paste -sd ' ' | dos2unix
}
export -f threewords

# Ensure we have a conference name
if [ -n "${1:-}" ]; then
  requested_conf="${1}"
  conf="$(date +"%Y")${1}"
else
  printf "Please provide conference name\n"
  exit 1
fi

# Check if that conference name already exists
for challenge in bluetooth/iBeacon bluetooth/classic_discoverable wifi/wifi_ap_client; do
  pushd "${challenge}" > /dev/null 2>&1
  if [ -e "src/conferences/${conf}.h" ]; then
    printf "%s/src/conferences/%s.h already exists, please remove it or pick a different name\n" "${challenge}" "${conf}"
    exit 1
  fi
  popd > /dev/null 2>&1
done
if [ -f "${conf}.txt" ]; then
  printf '%s.txt already exists, please remove it or pick a different name\n' "${conf}"
  exit 1
fi

for challenge in bluetooth/iBeacon bluetooth/classic_discoverable wifi/wifi_ap_client non-kitsune-foxes/fm_fox; do
  pushd "${challenge}" > /dev/null 2>&1
  printf "Rolling %s for %s... " "${challenge}" "${conf}"
  if [ -x make_conference ]; then
    ./make_conference "${requested_conf}"
    if [ ! -e "src/conferences/${conf}.h" ]; then
      printf "Something went wrong creating %s/src/conferences/%s.h, please scroll up\n" "${challenge}" "${conf}"
      exit 1
    fi
    ln -snf "conferences/${conf}.h" src/current_conf.h
  fi
  grep -e 'RFHS_CHALLENGE_NAME\|FOX_KEYWORDS\|NAME\|UUID\|MAC_ADDR\|FSSID\|CHANNEL' "src/current_conf.h" | \
    sed -e 's#{##' -e 's#}##' -e 's#0x##g' -e 's#, #:#g' -e 's#// ##' -e "s/#define //" | tee -a "${OLDPWD}/${conf}.txt" > /dev/null 2>&1
  printf "complete\n"
  popd > /dev/null 2>&1
done
printf "Formatting with conference name for %s... " "${conf}"
sed -i \
  -e "/RFHS_CHALLENGE_NAME/{h; s/.*/printf -- '-\\n----------------------------------------------------------------\\nConference: %s\\n' \"${conf}\"/e; G;}" \
  "${conf}.txt"
printf "complete\n"

printf "Adding instructions..."
sed -i -e "/FOX_KEYWORDS/{h; s/.*/printf -- '\n%s\n\n' \"\$(cat foxhunt_instructions.txt)\"/e; G;}" "${conf}.txt"
printf "complete\n"

printf "Seeding keys for %s... " "${conf}"
#this works despite shell check thinking it does not
#shellcheck disable=2016
sed -i -e 's/\(.*\)[F]OXFLAG\(.*\)/printf "%s%s%s\\n" \x22\1\x22 "\$(threewords)" \x22\2\x22/e' "${conf}.txt"
printf "complete\n"

sed -i '1iSet font to "Roboto Mono"' "${conf}.txt"

printf "Generation Complete\n"
