#!/bin/bash
set -e
set -u

# Ensure we have a conference name
if [ -n "${1:-}" ]; then
  conf="${1}"
else
  printf "Please provide conference name\n"
  exit 1
fi

# Check if that conference name already exists
for challenge in bluetooth/iBeacon bluetooth/classic_discoverable wifi/wifi_ap_client; do
  pushd "${challenge}" > /dev/null 2>&1
  if [ ! -e "src/conferences/${conf}.h" ]; then
    printf "%s/src/conferences/%s.h does not exist, unable to switch to this conference\n" "${challenge}" "${conf}"
    exit 1
  fi
  popd > /dev/null 2>&1
done

for challenge in bluetooth/iBeacon bluetooth/classic_discoverable wifi/wifi_ap_client; do
  pushd "${challenge}" > /dev/null 2>&1
  ln -snf "conferences/${conf}.h" src/current_conf.h
  popd > /dev/null 2>&1
done
printf "Switched to %s\n" "${conf}"
