; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  fastled/FastLED
; slower cpu means better battery life and slightly slower execution
board_build.f_cpu = 80000000L

; difficulty
[difficulty]
easy = -D EASY
hard = -D HARD
fiveeasy = -D FIVEEASY
fivehard = -D FIVEHARD

; mode
[mode]
client = -D CLIENT
ap = -D AP=AP

; board defines
;  if you add a board remember to add the led pin to include/rfhsledmacros.h
[m5atom]
board = m5stack-atom
[m5atoms3]
board = m5stack-atoms3
board_flags = -DARDUINO_USB_CDC_ON_BOOT=1
[m5stamps3]
board = m5stack-stamps3
board_flags = -DARDUINO_USB_CDC_ON_BOOT=1
[arduino_nano_esp32]
board= arduino_nano_esp32
board_flags = -DARDUINO_USB_CDC_ON_BOOT=1
[seeed-xiao-esp32c5]
board = seeed_xiao_esp32c5
; using the fork from pioarduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_flags = -DARDUINO_USB_CDC_ON_BOOT=1

; actual targets, four per board
[env:m5atom-easy-ap]
extends = m5atom
build_flags = ${difficulty.easy} ${mode.ap}
[env:m5atom-easy-client]
extends = m5atom
build_flags = ${difficulty.easy} ${mode.client}
[env:m5atom-hard-ap]
extends = m5atom
build_flags = ${difficulty.hard} ${mode.ap}
[env:m5atom-hard-client]
extends = m5atom
build_flags = ${difficulty.hard} ${mode.client}

; Client mode gets the wrong mac address, not sure why
[env:arduino-nano-esp32-easy-ap]
extends = arduino_nano_esp32
build_flags = ${difficulty.easy} ${mode.ap} ${arduino_nano_esp32.board_flags}
[env:arduino-nano-esp32-easy-client]
extends = arduino_nano_esp32
build_flags = ${difficulty.easy} ${mode.client} ${arduino_nano_esp32.board_flags}
[env:arduino-nano-esp32-hard-ap]
extends = arduino_nano_esp32
build_flags = ${difficulty.hard} ${mode.ap} ${arduino_nano_esp32.board_flags}
[env:arduino-nano-esp32-hard-client]
extends = arduino_nano_esp32
build_flags = ${difficulty.hard} ${mode.client} ${arduino_nano_esp32.board_flags} 

; Client mode gets the wrong mac address, not sure why
[env:seeed-xiao-esp32c5-easy-ap]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.easy} ${mode.ap} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-fiveeasy-ap]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.easy} ${difficulty.fiveeasy} ${mode.ap} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-easy-client]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.easy} ${mode.client} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-hard-ap]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.hard} ${mode.ap} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-fivehard-ap]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.hard} ${difficulty.fivehard} ${mode.ap} ${seeed-xiao-esp32c5.board_flags}
[env:seeed-xiao-esp32c5-hard-client]
extends = seeed-xiao-esp32c5
build_flags = ${difficulty.hard} ${mode.client} ${seeed-xiao-esp32c5.board_flags}

; known issues:
; serial isn't working
[env:m5atoms3-easy-ap]
extends = m5atoms3
build_flags = ${difficulty.easy} ${mode.ap} ${m5atoms3.board_flags}
[env:m5atoms3-easy-client]
extends = m5atoms3
build_flags = ${difficulty.easy} ${mode.client} ${m5atoms3.board_flags}
[env:m5atoms3-hard-ap]
extends = m5atoms3
build_flags = ${difficulty.hard} ${mode.ap} ${m5atoms3.board_flags}
[env:m5atoms3-hard-client]
extends = m5atoms3
build_flags = ${difficulty.hard} ${mode.client} ${m5atoms3.board_flags}

; known issues:
; serial isn't working
[env:m5stamps3-easy-ap]
extends = m5stamps3
build_flags = ${difficulty.easy} ${mode.ap} ${m5stamps3.board_flags}
[env:m5stamps3-easy-client]
extends = m5stamps3
build_flags = ${difficulty.easy} ${mode.client} ${m5stamps3.board_flags}
[env:m5stamps3-hard-ap]
extends = m5stamps3
build_flags = ${difficulty.hard} ${mode.ap} ${m5stamps3.board_flags}
[env:m5stamps3-hard-client]
extends = m5stamps3
build_flags = ${difficulty.hard} ${mode.client} ${m5stamps3.board_flags}
