#!/bin/sh

python3 -m pip install -U platformio

## Build 9999demo
for i in $(find . -name platformio.ini | grep -v '.pio'); do
  project="$(dirname -- "${i}")"
  pio run --silent --project-dir "${project}"
done
